version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Chicago
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Chicago
    groups:
      npm-development:
        dependency-type: development
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Chicago
    groups:
      python-development:
        patterns:
          - "*"
    open-pull-requests-limit: 5
